version: '3'

volumes:
  kittygram_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_data:/var/lib/postgresql/data
  backend:
    image: rt4otohub/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    image: rt4otohub/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: rt4otohub/kittygram_nginx
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media
